spring:
  application:
    name: jHuH
  ai:
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always
    openai:
      api-key: ${OPENAI_APIKEY}
    retry:
      on-http-codes:
        - 429
      backoff:
        initial-interval: 5s
        multiplier: 3
    vectorstore:
      mariadb:
        table-name: vector_store
        initialize-schema: true
  jpa:
    open-in-view: false
    show-sql: false

google:
  apikey: ${GOOGLE_APIKEY}
  cx: ${GOOGLE_CX}

ready2order:
  apikey: ${READY2ORDER_APIKEY}

shopify:
  domain: ${SHOPIFY_DOMAIN}
  token: ${SHOPIFY_TOKEN}
  read-only: false