DELIMITER //
CREATE FUNCTION UUID_TO_BIN(uuid CHAR(36))
    RETURNS BINARY(16)
BEGIN
    RETURN UNHEX(REPLACE(uuid, '-', ''));
END//
DELIMITER ;

INSERT INTO sync_vendor (id, name)
SELECT UUID_TO_BIN(UUID()), vendor
FROM sync_product
GROUP BY vendor;
COMMIT;

DROP FUNCTION UUID_TO_BIN;